# Generated by Django 5.0.4 on 2026-03-07 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('icon', models.CharField(blank=True, default='🍺', max_length=10, verbose_name='Icono (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_name', models.CharField(default='Backyard Bar', max_length=100, verbose_name='Nombre del bar')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='Eslogan')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Logo')),
                ('base_url', models.CharField(default='http://localhost:8000', help_text='URL que se incrustará en los códigos QR', max_length=200, verbose_name='URL base del sitio')),
                ('primary_color', models.CharField(default='#f5a623', max_length=7, verbose_name='Color primario')),
                ('secondary_color', models.CharField(default='#1a1a2e', max_length=7, verbose_name='Color secundario')),
                ('footer_text', models.TextField(blank=True, verbose_name='Texto del pie')),
            ],
            options={
                'verbose_name': 'Configuración del sitio',
                'verbose_name_plural': 'Configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Número de mesa')),
                ('name', models.CharField(blank=True, help_text='Ej: Terraza, Barra, VIP', max_length=50, verbose_name='Nombre/Alias')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_items/', verbose_name='Imagen')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('tags', models.CharField(blank=True, help_text='Ej: vegano, sin gluten, picante (separadas por coma)', max_length=200, verbose_name='Etiquetas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Item del menú',
                'verbose_name_plural': 'Items del menú',
                'ordering': ['order', 'name'],
            },
        ),
    ]
