# Generated by Django 5.0.4 on 2026-03-16 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Nº Ticket')),
                ('payment_method', models.CharField(choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia')], default='cash', max_length=20, verbose_name='Medio de pago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado')], default='pending', max_length=20, verbose_name='Estado')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('created_by', models.CharField(blank=True, max_length=100, verbose_name='Cobrado por')),
            ],
            options={
                'verbose_name': 'Venta en barra',
                'verbose_name_plural': 'Ventas en barra',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BarSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menuitem', verbose_name='Producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.barsale')),
            ],
        ),
    ]
